### ISSUE TITLE
setLevel(String)

### ISSUE THREAD

**Issue by fpedroza** [jonnyreeves/js-logger#100]
I'm trying to set the log level based on configuration coming from the backend. The backend value is a String: debug, info, warn, error, OFF.
`setLevel(String)` isn't supported. Am I missing something obvious? Any alternative suggestions?

I suppose I could switch based on the config value and call the corresponding `setValue(Level)` call.

**Comment by jybleau** [comment]
I do it like that: `Logger.setLevel(Logger[stringLevel])`
Assuming stringLevel is in upper case.

**Comment by jonnyreeves** [comment]
Personally I'd suggest a switch statement,  although @jybleau's solution also works if you have complete control and confidence over what the backend server is returning.
