### ISSUE TITLE
Create a method for setHandler and useDefaults

### ISSUE THREAD

**Issue by jreading** [jonnyreeves/js-logger#11]
I'm using this to log on the server and client and need to duplicate a bit of the useDefaults function in a setHandler function (to send back to the browser console). It would be nice if this was doable from the library itself.

**Comment by lucaspin** [comment]
@jonnyreeves I'm also using js-logger to log on the client and server and I'd like to know if you're going to include the addition from @khirakawa

**Comment by jonnyreeves** [comment]
Fixed in v1.2.0; you can now supplied a `formatter` function to `useDefaults` and mutate the `messages` Array as you see fit.
