### ISSUE TITLE
How to remove stacktrace from trace logs?

### ISSUE THREAD

**Issue by tonisives** [jonnyreeves/js-logger#113]
I like 3 levels of logging. Info for general information. Debug for more debug items. And trace for a lot of logs like all streaming messages. In js-logger, the Logger.trace also logs a stacktrace. This is too much information and I don't need it specifically.

Can you disable the stacktrace logging in Logger.trace?

**Comment by jonnyreeves** [comment]
Short answer: no, use a higher log level.

Longer answer: maybe.

jsLogger delegates the actual logging to the native browser functions (ie: `console.trace()`). It's possible you may be able to configure said native browser functions to disable stacktraces, but I'm not sure.

Alternatively you can write your own log handler implementation which delegates `ILogger.trace` calls through to the browser's native  `console.debug`, function which, as you said in your original issue, will not have a stacktrace appended.

Thanks for using this library, it's nice to know it still provides value almost 15 years after I wrote it.
