### ISSUE TITLE
setLevel(Logger.OFF) not working

### ISSUE THREAD

**Issue by ericntd** [jonnyreeves/js-logger#19]
I have the following but the log still get printed out:
```Javascript
var logger = Logger.get('BaseComponent');
Logger.get('BaseComponent').setLevel(Logger.OFF);
logger.setLevel(Logger.OFF);
```

**Comment by jonnyreeves** [comment]
Sorry for the slow response; there is already coverage around LogLevels, but if you can reproduce this in a failing test case I will take a look.

Thanks.
