### ISSUE TITLE
Messages Threshold

### ISSUE THREAD

**Issue by vert3x** [jonnyreeves/js-logger#21]
Hi,

Is there any Threshold method in js-logger? or an event that tells me this is the last message or something?

I want to set the handler to send messages to a WS endpoint, but not in every message I have, I want to more that more optimized so I thought about a threshold, something like ```threshold=5``` so after the 5th message I send the array of messages to the server then reset the array...

Thanks.

**Comment by jonnyreeves** [comment]
Sounds like you want to implement your own [debounced](https://davidwalsh.name/javascript-debounce-function) log handler?

Closing for now as I believe this can be fixed without modification to js-logger, feel free to re-open if you run into problems.
