### ISSUE TITLE
How to use with require or import?

### ISSUE THREAD

**Issue by hepiyellow** [jonnyreeves/js-logger#32]
Can you add to the README how to use the Logger without adding a `<script>` tag in the HTML but rather using it as a module with require or import statements?
So it isn't added to the global namespace.

**Comment by jonnyreeves** [comment]
Adding a what...?! Don't leave me hanging!

**Comment by hepiyellow** [comment]
Oops, forgot to wrap `<script>` in code back ticks. Edited original comment.

**Comment by timdiacon** [comment]
+1 on this please!

I'd love to load into my modules in require.js but can't work out how to do it :-(

**Comment by jonnyreeves** [comment]
You just need to make a `require` call for the `js-logger` module:

```js
// CommonJS import
var jsLogger = require('js-logger');

// Usage.
var namedLogger = jsLogger.get('named-logger');
namedLogger.info("hello world!")
```

If you are using ES6 modules, you can use the `import` keyword:

```js
import jsLogger from 'js-logger';
```

I have personally used JSLogger with browserify and webpack; I'm pretty sure I had it working with requirejs back in the day (:

**Comment by timdiacon** [comment]
Thanks for reply, so I guess I should be using either browserify or webpack ;-)

However, and this is probably more a lack of understanding about how requirejs works...
How do I set useDefaults() on the logger in my main.js and then have that setting persist on instances of the logger I require into my modules?

The only way I could make it work was by creating a wrapper module around jslogger which has a getter to retrieve the logger instance but I'm guessing that is not what I'm supposed to be doing?

**Comment by jonnyreeves** [comment]
If requirejs works the same as browserify and webpack; then modules are statically imported (in the java sense), so mutations made in one place will be picked up elsewhere, ie: you can import jsLogger in your entrypoint and invoke `useDefaults()` after which all subsequent invocation of jsLogger will be configured accordingly.
