### ISSUE TITLE
Logger.debug output

### ISSUE THREAD

**Issue by nusson** [jonnyreeves/js-logger#41]
Chrome (I'm on v.54) have some usefull filters (log, info, debug...)
`Logger.log()` output in `log` filter
but `Logger.debug()` don't output in `debug` filter

**Comment by jonnyreeves** [comment]
PRs welcome :)

**Comment by nusson** [comment]
Yep i know ;)
Pretty busy right now but I like your lib so I might help ;)

**Comment by jonnyreeves** [comment]
Fixed by #34
