### ISSUE TITLE
Question : stack trace

### ISSUE THREAD

**Issue by nusson** [jonnyreeves/js-logger#42]
When using default console, we can see where in our code there is this log (error whatever)
but since this plugin use `Function.prototype.apply.call(hdlr, console, messages);`
all logs are from `logger.js:181`

So, is there a way to see where is our log from ?

**Comment by jonnyreeves** [comment]
Nope, I'm afraid not.  The only thing you could do determine the call site is to create a new `Error` instance and then walk up the stack-trace using string manipulation - however this will have a significant performance penalty.
