### ISSUE TITLE
Mention babel-plugin-js-logger in README.md

### ISSUE THREAD

**Issue by core-process** [jonnyreeves/js-logger#44]
Hi,

hope you like the following nice babel plugin:

https://www.npmjs.com/package/babel-plugin-js-logger
https://github.com/core-process/babel-plugin-js-logger

Would you like to add a reference to your README.md?

Thanks!

Niklas

**Comment by jonnyreeves** [comment]
Nice plugin, feel free to raise a pr against the jslogger readme

**Comment by core-process** [comment]
https://github.com/jonnyreeves/js-logger/pull/45

**Comment by core-process** [comment]
Thanks! :+1:

**Comment by core-process** [comment]
@jonnyreeves Have a look at our [logger-example](https://github.com/core-process/logger-example) project. It is a self-contained showcase on how to use js-logger within your backend and frontend code efficiently.
