### ISSUE TITLE
Declaration file not recognized by typescript compiler

### ISSUE THREAD

**Issue by akieling** [jonnyreeves/js-logger#53]
I'm using typescript 2.3.4. When I declare a triple-slash directive pointing to `logger.d.ts`:
```
/// <reference path="../node_modules/js-logger/src/logger.d.ts" />
```
and write `Logger` in my source file, the compiler doesn't recognize it and throws the following error:
```
error TS2304: Cannot find name 'Logger'.
```

**Comment by jonnyreeves** [comment]
@akieling Are you still experiencing an issues, or were you able to resolve this yourself?

I am successfully using js-logger in a TypeScript 2.x project, however we are simplying `import`'ing js-logger and relying on the compiler to automatically locate the relevant typings.

**Comment by akieling** [comment]
@jonnyreeves I'm fine. I've also configured the typings location and the compiler is finding them alright. Thanks.

**Comment by Nxt3** [comment]
How did you resolve this? I'm having the same issue. Ran `yarn add js-logger` and then in a component in Angular I have `import { jsLogger } from 'js-logger';` and I get the following error upon compilation:

`Module '"/Users/user/code/app_folder/node_modules/js-logger/src/logger"' has no exported member 'jsLogger'.`

**Comment by timm-gs** [comment]
I was able to get a typed import with:

```ts
import Logger = require("js-logger");
```

But there seems no way to import the interfaces from the module yet.

**Comment by pgorczynski-df** [comment]
The correct way to make an ES6 import after running `npm install js-logger` is
`import * as Logger from "js-logger";`
and the you just use
` Logger.error("Yada yada yada");`
