### ISSUE TITLE
getLevel in docs but not in release

### ISSUE THREAD

**Issue by Koed00** [jonnyreeves/js-logger#54]
Methods like getLevel are in the documentation but not in the current release.
Could you please do a release?

**Comment by francis-lookback** [comment]
Yeah, also `console.debug` support is in the latest commit but not in the 1.3.0 release.

**Comment by jonnyreeves** [comment]
Released 1.4.0 - sorry for the delay - my wife and I just had our second child at the start of June :)

**Comment by francis-lookback** [comment]
Oh wow, congratulations! 🎉 

Thanks for the version bump. 👍
Also, loving that profile pic 😸
