### ISSUE TITLE
log levels

### ISSUE THREAD

**Issue by flobee** [jonnyreeves/js-logger#60]
Hi i just checked the code and i like the logger :)

My question is: would it be more common to use the standard log levels like BSD syslog levels? 

There is a rfc: https://tools.ietf.org/html/rfc3164#section-4.1.2 (Page 8, last lines) Log level 0 - 7 for the severity.
```
           0       Emergency: system is unusable
           1       Alert: action must be taken immediately
           2       Critical: critical conditions
           3       Error: error conditions
           4       Warning: warning conditions
           5       Notice: normal but significant condition
           6       Informational: informational messages
           7       Debug: debug-level messages
```
If you agree i can fork it if you like and send a pull request. 

Kind regards

**Comment by jonnyreeves** [comment]
Hi @flobee - thanks for reaching out.

The log levels provided by js-logger map to those fond on the Chrome and Firefox `console` object and will be familiar to developers who have made use of them before.  IMHO, this familiarity is preferable to aligning to RFC3164 and/or introducing additional methods and aliases.

**Comment by flobee** [comment]
Ah, ok. I did not know that FF or Chrome has those implementation and syslog is really server releated and not js "frontend". i wonder how node will handle it. hmm :) thx for reply! :) I think switching to different levels when using js for the frontend.
Kind regards
