### ISSUE TITLE
logger.debug('...') calls don't work when level is set to logger.DEBUG

### ISSUE THREAD

**Issue by pavle-goloskokovic** [jonnyreeves/js-logger#61]
`logger.debug('...')` calls are NOT printed when level is set to `logger.DEBUG` when using `v1.4.1`.
`logger.info('...')` and above are printed.
With `v1.3.0` it works fine. 

This is the basic functionality of a logger, if this doesn't work than it's pretty much useless :P 

For the project where I'm using it I'm writing my code in `TypeScript` and compiling it with latest version of `webpack`, it might be relevant. 
Will be using `v1.3.0` until this issue is resolved.

Thanks!

**Comment by jonnyreeves** [comment]
Hi, sorry to see you are experiencing problems.

I think this might be an environmental issue as [this test case](https://github.com/jonnyreeves/js-logger/blob/master/test-src/loggertests.js#L30) looks like it covers your repro case above?

To help debug this further could you let me know which browser you are using?

Thanks

**Comment by pavle-goloskokovic** [comment]
I'm using Chrome Version 61.0.3163.91 (Official Build) (64-bit) (latest version at the time of writing).
The test code looks correct, could you try running it in Chrome?

But nevertheless I doubt it is an environmental issue since the v1.3.0 works as expected and v1.4.1 has this issue.
My guess is that changes that were made for the later version are cause of it.

**Comment by jonnyreeves** [comment]
Ah ok, I think I know what the problem might be. v1.4 of js-logger introduced a change which rows l routed `DEBUG` level messages through to `console.debug()` when that method is present.

Is it possible that your console log filter setting in Chrome Developer Tools is filtering these messages out?

**Comment by pavle-goloskokovic** [comment]
@jonnyreeves that was it.
By default Chrome only shows `INFO` messages and above, it has to be explicitly selected to show `DEBUG` and browser specific messages from a dropdown menu:

![image](https://user-images.githubusercontent.com/7340300/30648188-c04337ca-9e1d-11e7-85ab-9c7204a15fc2.png)

I guess this is how it is supposed to work form now on. 
Thanks for helping out!
