### ISSUE TITLE
Logging into plain text files

### ISSUE THREAD

**Issue by ashishd751** [jonnyreeves/js-logger#72]
Hi,
I was wondering if this library provides logging data into plain text files instead of the regular web console.

The idea is that if we could log onto separate files, we could have a look at them at our own leisure, let alone send them over to someone for debugging.

I was expecting something like - 
`var myLogger = new Logger('/path/to/txt/file/where/data/will/be/logged')`

As per the above line, all logs will be saved onto that file. If the file doesn't already exist, a new file will be created.

Thanks in advance,
Ashish Deshpande

**Comment by jonnyreeves** [comment]
You can achieve this by writing your own [logHandler function](https://github.com/jonnyreeves/js-logger/tree/master#log-handler-functions).
