### ISSUE TITLE
The 1.5.0 version does not work with typescript 3.1.3 (EDIT 1.4.1 works)

### ISSUE THREAD

**Issue by tanneess** [jonnyreeves/js-logger#85]
The 1.5.0 and 1.4.1 version does not work with typescript 3.1.3. I have not tested other versions. Here is the error message I get.

...../node_modules/js-logger/src/logger.d.ts
(112,1): An export assignment cannot be used in a module with other exported elements.

**Comment by Naresh-Nelavalli** [comment]
I tried and it doesn't work with the import from min file:
import { Logger } from 'logger';

**Comment by tanneess** [comment]
Problem is only with 1.5.0. Initial assessment was wrong. It seems that `export = ` is no longer supported on latest typescript if there are other exports in the file. So the additional export of ILogger is to blame here.
I am still looking for how to export ILogger correctly but a quickfix would be to stop exporting ILogger. A workaround is to stay with 1.4.1

**Comment by tanneess** [comment]
stop exporting ILogger #87
