### ISSUE TITLE
Request for api to set log-level of the Profile calls

### ISSUE THREAD

**Issue by toddpi314** [jonnyreeves/js-logger#93]
Currently, they appear to be pumping out on the INFO level by default.

**Comment by jonnyreeves** [comment]
Thanks for raising this issue @toddpi314, please could you describe your use case?

The philosophy behind the default LogHandler is to mimic the behaviour of the main browsers (a kind of greatest common divisor). IIRC Chrome and friends output trace calls at info level and offer no way for the user to configure this.

If you would like complete control over the LogHandler then I would suggest creating your own implementation and using the `setHandler()` method so js-logger makes use of it.

Please feel free to reopen if you feel I have missed anything or if you have an alternative suggestion
