### ISSUE TITLE
When logging the line number comes from the logger instead the file where the logger is used

### ISSUE THREAD

**Issue by kanso-git** [jonnyreeves/js-logger#96]
I 'm using the js-logger in my project, but as you can see in the below logging records , the line number is referring to a line number in the logger.js file .

how can I get the line number of the file where the logging is enabled?

`
 DEBUG-Wed, 02 Oct 2019 09:19:46 GMT Desk polling done at Wednesday, October 2nd 2019, 11:19:46 am logger.js:188 

DEBUG-Wed, 02 Oct 2019 09:19:49 GMT Desk polling done at Wednesday, October 2nd 2019, 11:19:49 am logger.js:188 `

**Comment by jonnyreeves** [comment]
I'm afraid this is a known limitation of the library. Happy to accept a PR which adds an FAQ to the readme if you feel it would help others.

Wishing you a great day.
