### ISSUE TITLE
How do I extend the logger?

### ISSUE THREAD

**Issue by k2042** [jonnyreeves/js-logger#97]
By default, Logger.get() returns ILogger which is only good for calling the particular logging methods. As far as I found, I can't even set some additional values to the context.

What is the proper "entry point" if I want to extend js-logger, like adding additional error levels, logging methods for the new levels, wrapping or overriding the base methods, while having it (hopefully) strongly typed?

**Comment by jonnyreeves** [comment]
Sorry for the late reply, but in all honestly the answer at this stage in the projects lifecycle would be to fork it to meet your specific needs.
