### ISSUE TITLE
yarn?

### ISSUE THREAD

**Issue by davvit** [jonnyreeves/js-logger#99]
```
>yarn add js-Logger

yarn add v1.22.4
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/js-Logger: Not found".
```

**Comment by Globolobo** [comment]
> ```
> >yarn add js-Logger
> 
> yarn add v1.22.4
> [1/4] Resolving packages...
> error An unexpected error occurred: "https://registry.yarnpkg.com/js-Logger: Not found".
> ```

`yarn add js-logger`

**Comment by jonnyreeves** [comment]
Sorry folks I'm not sure what you are asking for here 🐱
